[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "autobahn>=24.4.2",
    "pyopenssl>=25.1.0",
    "service-identity>=24.2.0",
    "twisted>=24.11.0",
]
